// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZsmchfE6Sg6ki9gdyVsLqWRpl8cdwMrU',
    appId: '1:669568193320:web:eeaae22143fddb94ddb61d',
    messagingSenderId: '669568193320',
    projectId: 'flutter-tareas-61576',
    authDomain: 'flutter-tareas-61576.firebaseapp.com',
    storageBucket: 'flutter-tareas-61576.appspot.com',
    measurementId: 'G-H5ZZPY895P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwt03A7ymXwuGMXi_91Ycdv01Wy2PwXl8',
    appId: '1:669568193320:android:62fe0f4ea7efbd10ddb61d',
    messagingSenderId: '669568193320',
    projectId: 'flutter-tareas-61576',
    storageBucket: 'flutter-tareas-61576.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZsmchfE6Sg6ki9gdyVsLqWRpl8cdwMrU',
    appId: '1:669568193320:web:3c2f5cc20e117333ddb61d',
    messagingSenderId: '669568193320',
    projectId: 'flutter-tareas-61576',
    authDomain: 'flutter-tareas-61576.firebaseapp.com',
    storageBucket: 'flutter-tareas-61576.appspot.com',
    measurementId: 'G-PNZDHGWFE3',
  );

}